[project]
name = "nhp.databricks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "databricks-connect==17.3.*",
    "ipywidgets>=8.1.9",
    "jupyter>=1.1.1",
    "nhp-model==6.0.0",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
